name: Build SO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v3

    - name: Baixar Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
        unzip android-ndk-r27d-linux.zip
        mv android-ndk-r27d $HOME/android-ndk

    - name: Compilar para ARM64
      run: |
        $HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
        -shared -o libnebulakernel.so libnebulakernel.c

    - name: Salvar artefato
      uses: actions/upload-artifact@v3
      with:
        name: libnebulakernel
        path: libnebulakernel.so
